galaxy_info:
  role_name: ansible_role_prometheus
  namespace: acme
  author: Nastya and Artttezy
  description: my desc
  company: ITMO

  license: BSD

  min_ansible_version: 2.14.0

  galaxy_tags: []

dependencies: []